export const MENTOR_DASH_DETAIL = "MENTOR_DASH_DETAIL"
export const MENTOR_DASH_DETAIL_SUCCESS = "MENTOR_DASH_DETAIL_SUCCESS"
export const MENTOR_DASH_DETAIL_API_ERROR = "MENTOR_DASH_DETAIL_API_ERROR"
