export const MENTOR_AVAILABILITY = "MENTOR_AVAILABILITY"
export const MENTOR_AVAILABILITY_SUCCESS = "MENTOR_AVAILABILITY_SUCCESS"
export const MENTOR_AVAILABILITY_API_ERROR = "MENTOR_AVAILABILITY_API_ERROR"
