export const STUDENT_ASSIGNED_SESSION = "STUDENT_ASSIGNED_SESSION"
export const STUDENT_ASSIGNED_SESSION_SUCCESS = "STUDENT_ASSIGNED_SESSION_SUCCESS"
export const STUDENT_ASSIGNED_SESSION_API_ERROR = "STUDENT_ASSIGNED_SESSION_API_ERROR"
