export const MENTOR_ASSIGNED_SESSION = "MENTOR_ASSIGNED_SESSION"
export const MENTOR_ASSIGNED_SESSION_SUCCESS = "MENTOR_ASSIGNED_SESSION_SUCCESS"
export const MENTOR_ASSIGNED_SESSION_API_ERROR = "MENTOR_ASSIGNED_SESSION_API_ERROR"
