export const PHONE_LOGIN_USER = "PHONE_LOGIN_USER"
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS"

export const PHONE_LOGOUT_USER = "PHONE_LOGOUT_USER"
export const PHONE_LOGOUT_USER_SUCCESS = "PHONE_LOGOUT_USER_SUCCESS"
export const PHONE_API_ERROR = "PHONE_LOGIN_API_ERROR"
