export const MENTOR_SESSION_REPORT = "MENTOR_SESSION_REPORT"
export const MENTOR_SESSION_REPORT_SUCCESS = "MENTOR_SESSION_REPORT_SUCCESS"
export const MENTOR_SESSION_REPORT_API_ERROR = "MENTOR_SESSION_REPORT_API_ERROR"
