export const MS_STUDENT_PROFILE = "MS_STUDENT_PROFILE"
export const MS_STUDENT_PROFILE_SUCCESS = "MS_STUDENT_PROFILE_SUCCESS"
export const MS_STUDENT_PROFILE_API_ERROR = "MS_STUDENT_PROFILE_API_ERROR"
