export const STUDENT_DASH_DETAIL = "STUDENT_DASH_DETAIL"
export const STUDENT_DASH_DETAIL_SUCCESS = "STUDENT_DASH_DETAIL_SUCCESS"
export const STUDENT_DASH_DETAIL_API_ERROR = "STUDENT_DASH_DETAIL_API_ERROR"
