export const STU_SUBJECT_EXPERT = "STU_SUBJECT_EXPERT"
export const STU_SUBJECT_EXPERT_SUCCESS = "STU_SUBJECT_EXPERT_SUCCESS"
export const STU_SUBJECT_EXPERT_API_ERROR = "STU_SUBJECT_EXPERT_API_ERROR"
