export const MENTOR_SESSION_DASH = "MENTOR_SESSION_DASH"
export const MENTOR_SESSION_DASH_SUCCESS = "MENTOR_SESSION_DASH_SUCCESS"
export const MENTOR_SESSION_DASH_API_ERROR = "MENTOR_SESSION_DASH_API_ERROR"
