export const MS_EDIT_MENTOR_PROFILE = "MS_EDIT_MENTOR_PROFILE"
export const MS_EDIT_MENTOR_PROFILE_SUCCESS = "MS_EDIT_MENTOR_PROFILE_SUCCESS"
export const MS_EDIT_MENTOR_PROFILE_API_ERROR = "MS_EDIT_MENTOR_PROFILE_API_ERROR"

